Repository yesnaga/yesnaga, pull requests merged in 2020-10, with the labels that each got.

#9 Add CodeQL to analyse code and dependencies
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#8 Persistence and API routes for games & moves
  .gitignore
  lib/Board.js
  lib/Board.test.js
  lib/BoardFactory.js
  lib/BoardFactory.test.js
  lib/Errors.js
  lib/Game.js
  package-lock.json
  package.json
  routes/api/game.js
  routes/api/index.js
  routes/api/move.js
Labels: enhancement

#13 Update README.md
  README.md
Labels: documentation

#15 Add Menu
  lib/Game.test.js
  public/scripts/constants.js
  public/scripts/game.js
  public/scripts/main.js
  public/scripts/menu.js
  public/shapes/disc.js
  public/shapes/hud.js
  public/stylesheets/style.css
  routes/api/move.js
  views/board.pug
Labels: Waiting for review

#19 Add confetti when winning
  public/scripts/menu.js
  public/shapes/hud.js
Labels: Waiting for review
